version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14.4

    working_directory: /go/src/github.com/veggiedefender/browsertunnel
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
